### ISSUE TITLE
the game is down

### ISSUE THREAD

**Issue by makc** [felixmariotto/Edelweiss#10]
![god damn it](https://user-images.githubusercontent.com/242577/80196386-a5ad6800-861d-11ea-895e-f29909393eb6.png)

see, this is exactly the shit I knew was going to happen when I 1st forked your repo.

**Comment by felixmariotto** [comment]
No worries, it's just an issue of payment with AWS. I changed the payment credit card when I relocated recently, and apparently the first payment with a MasterCard must be done manually. It should work now, I'm not in front of my PC so I can't check, let me know.

**Comment by makc** [comment]
Nope, still down. You can check on your phone by going to https://edelweiss-game.s3.eu-west-3.amazonaws.com/skybox/px.jpg for example.

**Comment by felixmariotto** [comment]
Well now it seems that there is another issue with AWS... I contacted the support, sorry about that, I hope you can still work on your editor on your side ?

**Comment by makc** [comment]
my entire fork is working :) so no problem there

**Comment by makc** [comment]
ok, your game is up, and I see the plant is fine, so that is probably in my version of 0.glb
