### ISSUE TITLE
brown plants

### ISSUE THREAD

**Issue by makc** [felixmariotto/Edelweiss#11]
I have finally caught bad plants in your version, too, so it is not something I did 😅 phew.

![Screen Shot 2020-04-26 at 3 50 27 ](https://user-images.githubusercontent.com/242577/80295223-609a4a80-8771-11ea-9868-f595921c101f.png)

(also **NOTE** the rock has suspiciously dark triangle, too)

![Screen Shot 2020-04-26 at 3 50 43 ](https://user-images.githubusercontent.com/242577/80295225-62fca480-8771-11ea-84e3-17614f7d84c1.png)

Since as you say they appear based on camera angle, I think there is duplicated geometry issue, and 2nd copy has bad UVs.

**Comment by felixmariotto** [comment]
![error1](https://user-images.githubusercontent.com/46470486/80300280-89cfd080-879b-11ea-9459-4837fc636bbb.jpg)
![error2](https://user-images.githubusercontent.com/46470486/80300283-8dfbee00-879b-11ea-8fac-a0a7850a11c5.jpg)

There was indeed an issue with my UV mapping of these plants, good catch, thanks for spotting that. You can see on my screenshots that some faces were mapped on the brown corner. I quickly checked the other files, and spotted another one near the dash power-up, that I fixed too. I also replaced cave-A with your version, which is nicer.

**Comment by felixmariotto** [comment]
By the way, I've seen the boat, if you do what I think you will do with it, it will be awesome !

**Comment by makc** [comment]
Ha ha, yes, I intend to finish this with a boat trip to level 2 or something

**Comment by makc** [comment]
> also replaced cave-A with your version, which is nicer.

dont forget to patch the json, so that they could climb the tile

**Comment by felixmariotto** [comment]
Woops thanks, it's updated
