### ISSUE TITLE
No foliage on climbable wall

### ISSUE THREAD

**Issue by makc** [felixmariotto/Edelweiss#14]
I think it might be related to your recent 4.glb edit:

![Screen Shot 2020-04-28 at 0 03 44 ](https://user-images.githubusercontent.com/242577/80425419-dfaf9000-88e3-11ea-98a0-d449a2dad854.png)
(at the bottom on the right)

**Comment by felixmariotto** [comment]
OK I've updated again a lot of files : 

0.glb : 
- closed cave entrance tunnel for shadows
- flipped some faces in the big house roof
- closed all bottom of roof, so when seen from bottom (when jumping), we don't see the sky

1.glb : 
- corrected a tree trunk color
- closed the tent
- corrected a plant texture map in the field
- closed cave entrance for shadows
- closed openings in terrain meshes through which players could see the skybox

3.glb : 
- closed the tent

4.glb : 
- fixed my mistake that you mentioned above

5.glb : 
- elongate the lowest part of the river because skybox was visible from on point at the top right
- close tent
- close inside cave entrance

6.glb : 
- close bottom of volume in front of big waterfall, for shadow

7.glb:
- close little hole in terrain
- close tent

8.glb:
- close tent
- close cave gate for shadow

9.glb:
- close tent
- close cave gate for shadow

10.glb:
-close cave gates for shadow

11.glb:
- close tent

13.glb:
- close tents
- close dev house gate for shadow
- fix faces normal on dev home house
- add plane under the roof so one can't see the sky from the bottom

**Comment by felixmariotto** [comment]
It was a lot of little issues with the map that I've been wanting to fix for some time, especially the light in the cave gates was very annoying.

**Comment by makc** [comment]
> 0.glb :
> closed cave entrance tunnel for shadows

not sure if you mean what I think you do, but I can still see the sky there on super-wide angles:
![Screen Shot 2020-04-28 at 19 20 14 ](https://user-images.githubusercontent.com/242577/80517591-9b74cc00-8985-11ea-82f8-b6a0516baa0e.png)

but probably noone is playing at these angles, so it is ok.

**Comment by makc** [comment]
> close tent 

I tried to work around this by duplicating the triangles inside the tents and flipping their normals:
![Screen Shot 2020-04-28 at 19 26 50 ](https://user-images.githubusercontent.com/242577/80518181-6d43bc00-8986-11ea-90c5-127874cc40a8.png)
![Screen Shot 2020-04-28 at 19 27 09 ](https://user-images.githubusercontent.com/242577/80518183-6fa61600-8986-11ea-9b78-55e151e5344c.png)
however, it has the same shadow problem as double-sided materials on characters, and also closing the tent makes it look like there may be some stuff like supplies etc, while you can see the tent is empty if it is open, so yeah - good idea :)

**Comment by felixmariotto** [comment]
I mean this : 
![2020-04-28_192734](https://user-images.githubusercontent.com/46470486/80518108-5604ce80-8986-11ea-91b6-68d40a3d60ab.jpg)
Before there was nothing here, so the light came through. After the dash I closed completely like you suggest though, because the sky was visible even without wide angle.

**Comment by makc** [comment]
...except this thing does not really look like a tent now :D what is this, looks like a stone wrapped into the tent
![Screen Shot 2020-04-28 at 19 27 09 ](https://user-images.githubusercontent.com/242577/80519126-cc560080-8987-11ea-9557-cde242325e3c.png)
![Screen Shot 2020-04-28 at 19 37 00 ](https://user-images.githubusercontent.com/242577/80519131-ccee9700-8987-11ea-9c57-795a41100063.png)

**Comment by makc** [comment]
if it is closed it should be flat and tight, no?

**Comment by felixmariotto** [comment]
Yeah you're right I will update this. Maybe it's better if I add a black line like a zip don't you think ?

**Comment by felixmariotto** [comment]
![2020-04-28_193911](https://user-images.githubusercontent.com/46470486/80519343-1dfe8b00-8988-11ea-80c9-3834aac966a8.jpg)
I've shaded smooth the faces of the hero and the lady

**Comment by felixmariotto** [comment]
And check out the things I've done with the caves light and the limit plane. I don't know now it's maybe too dark, let me know what you think.

**Comment by makc** [comment]
Well it sort of makes sense that it is dark in there, but if we go by the sense, it should be way darker and the hero needs a torch or something to even see anything. and, I liked the previous lighting better, not so much because it was brighter but because it had less contrast.

**Comment by felixmariotto** [comment]
Yes I agree, I will see if it's better with a bit more ambient and less point light

**Comment by makc** [comment]
funny how even fog used to light up the shadows - see it kicking in around the mine shaft entrance in the back:
![Screen Shot 2020-04-28 at 19 58 19 ](https://user-images.githubusercontent.com/242577/80521244-ff4dc380-898a-11ea-8481-177dbcb267fb.png)
vs current version:
![Screen Shot 2020-04-28 at 19 57 35 ](https://user-images.githubusercontent.com/242577/80521280-112f6680-898b-11ea-9ef0-6b1b7a0276ba.png)

Btw, maybe instead of hacking emissive params just add the point light to the edelweiss? If you do that, the cave lighting for 1st cave might solve itself, but you probably need to disable shadws on the edelweiss itself

**Comment by felixmariotto** [comment]
I've changed the values, now it looks much like it did before, but without the problem of the fog shading the "cutting plane" of the cave

**Comment by felixmariotto** [comment]
by the way I've seen [this shader](https://discourse.threejs.org/t/unlit-water-shader-with-foam/11641) by mugen, do you think it would impact performance a lot if we used it for the see and the river and waterfalls ?

**Comment by makc** [comment]
well it looks like postprocessing so even if it impacts performance it is going to be optimized away by your optimizer, I guess ?

**Comment by felixmariotto** [comment]
Yes, I will try to add his shader later.
I've updated the tents again, I think I will not update the map files for a while now, so you can safely add your boats and water cartridges if you want =P
![2020-04-28_223809](https://user-images.githubusercontent.com/46470486/80539425-c5d78100-89a7-11ea-8035-7221ea6ee164.jpg)

**Comment by makc** [comment]
I think if you bump his thread and ask how to wrap his shador into ShaderPass he might do like 50% of the job for you ;)

**Comment by makc** [comment]
> I think I will not update the map files for a while now, so you can safely add your boats

I think I will actually re-do the way glb-s are loaded in my fork, so that different people would not have to change each other glb-s.

**Comment by makc** [comment]
> re-do the way glb-s are loaded in my fork

Oh man, this is going to be super-awesome. Too bad I cant finish this today, as I have some real work to do, but this is really going to be the best thing since sliced bread, at no cost whatsoever :) Cant wait to add these guys all over the place:

![Screen Shot 2020-04-29 at 14 07 00 ](https://user-images.githubusercontent.com/242577/80594290-06281500-8a23-11ea-8ebd-d2d6b317c2f3.png)

**Comment by felixmariotto** [comment]
XD I love it, very suited in the area between the first camper and the waterfall. Are they animated ?

**Comment by makc** [comment]
> Are they animated ?

crap, I thought so, but [they](https://free3d.com/3d-model/cartoon-low-poly-sheep-211607.html) arent. no matter, Ive found [another low poly sheep](https://www.turbosquid.com/3d-models/sheep-low-poly-3d-model-1222875) that is:

![Baah](https://static.turbosquid.com/Preview/001222/875/FB/sheep-low-poly-3D-model_Z.jpg)
![Screen Shot 2020-04-29 at 16 15 47 ](https://user-images.githubusercontent.com/242577/80606616-d2ee8180-8a34-11ea-81aa-45e2f71e0a06.png)

**Comment by felixmariotto** [comment]
To be honest I prefer the second one anyway, I like the lazy face

**Comment by makc** [comment]
@felixmariotto another assets issue for you: glb 0 and 1 now have visible seam. you probably need some overlap there:
![Screen Shot 2020-05-01 at 0 13 19 ](https://user-images.githubusercontent.com/242577/80764446-06b6cd80-8b41-11ea-9786-49228fbc5f75.png)
![Screen Shot 2020-05-01 at 0 14 28 ](https://user-images.githubusercontent.com/242577/80764448-07e7fa80-8b41-11ea-8159-d209bf370395.png)

**Comment by makc** [comment]
@felixmariotto so, here is what the system looks like:

![Screen Shot 2020-05-01 at 21 41 50 ](https://user-images.githubusercontent.com/242577/80836470-1abc0700-8bf5-11ea-954e-09139c5f8a7b.png)

you just create new inert cube, and put the glb url in its tag. the glb is then loaded. you can move the cube around, and the model will follow. I hacked ?r=<degrees> parameter in, too, to rotate it around vertical axis in case you load multiple instances of the same asset:

![Screen Shot 2020-05-01 at 21 42 24 ](https://user-images.githubusercontent.com/242577/80836666-8900c980-8bf5-11ea-8a0e-52c7a719182a.png)

that is it, you now have perfectly collidable object, if you save the json. also you can now quit debug mode and play as you would normally:

![Screen Shot 2020-05-01 at 21 42 51 ](https://user-images.githubusercontent.com/242577/80836745-b2b9f080-8bf5-11ea-9437-4b9f5f891d50.png)

you can see how with this you can have a bunch of assets that you could just add where ever, without editing main glbs. rocks, trees, tables, statues, whatever. you could even add another old lady that will not talk to you.

unfortunately there is some bug that duplicates these objects when you go in/out the caves, so I cant commit yet. but I will soon :)

**Comment by felixmariotto** [comment]
> also you can now quit debug mode and play as you would normally

Awesome. I found that the debug mode is especially useful for teleporting, but when you want to play to have a look at how your map looks like, it's better without the "matrix" grid.

> I hacked ?r= parameter in, too, to rotate it around vertical axis in case you load multiple instances of the same asset

I see what you mean. but would you mind adding an input tag above the "OK" so the user can input angles in degrees (and scale scalar maybe) ? Because even though personally I would get away with this parameter, I don't think ultimately players will get the hang of it.

> hmmm can sheep even be that big?

I think it's fine, for me the hero is a child anyway. I don't know if you noticed but my avatar at the top is much bigger that the hero ! I don't bother too much about this.

**Comment by makc** [comment]
![Screen Shot 2020-05-02 at 0 23 00 ](https://user-images.githubusercontent.com/242577/80845997-3e8a4780-8c0b-11ea-8f59-18763b8011d3.png)

made it 20% smaller, I think Im going to leave it at that. now to find the bug....

> my avatar at the top is much bigger that the hero

well you are sitting there, which is why I did not notice. 

> adding an input tag above the "OK" so the user can input angles in degrees (and scale scalar maybe) 

it does make sense what you are saying. at the moment I use the same dialog for tiles and cubes, so I am a bit lazy about this. but then, if you backport this system, you are free to enhance it ;) 

> the "matrix" grid

Ive got tired of this matrix effect that I added as a one time joke, but when I tried to replace it with solid fills again, it looked even more "in the way", so that is how I kept it for so long:
![Screen Shot 2020-04-19 at 13 36 29 ](https://user-images.githubusercontent.com/242577/80846429-6cbc5700-8c0c-11ea-9e76-9a049be6cfe3.png)
![Screen Shot 2020-04-19 at 13 37 18 ](https://user-images.githubusercontent.com/242577/80846430-6ded8400-8c0c-11ea-8c46-84fcfe192b64.png)

**Comment by makc** [comment]
ok, so these changes are live now.

btw, the whole thing now is a bit of a mess because it has to support both this new system and an old system where a fixed number of assets was preloaded for npcs/bonuses. if you get rid of that one in favor of new system (with the mapping from existing tags to glb urls hardcoded somewhere in the code), you would get an ability to add npcs or bonuses at will, including the caves.... unlike right now where you could remove npc and add it back, but not add more than there was originally.
