### ISSUE TITLE
mountain.json issues

### ISSUE THREAD

**Issue by makc** [felixmariotto/Edelweiss#16]
Here are some screenshots I had savd, I went ahead and fixed these tiles to match the assets earlier, but now with your changes I guess I will have to double-check. And so should you, since you cant just copy my json. Because of the boat.
![Screen Shot 2020-04-17 at 10 59 06 ](https://user-images.githubusercontent.com/242577/80551960-7ef88400-89c5-11ea-9f35-120a2b5f3210.png)
![Screen Shot 2020-04-25 at 14 36 59 ](https://user-images.githubusercontent.com/242577/80551965-80c24780-89c5-11ea-9215-6bf939f3c4bb.png)
![Screen Shot 2020-04-25 at 14 37 17 ](https://user-images.githubusercontent.com/242577/80551967-815ade00-89c5-11ea-986c-61fda93bb1aa.png)
![Screen Shot 2020-04-25 at 14 59 46 ](https://user-images.githubusercontent.com/242577/80551969-81f37480-89c5-11ea-8b5f-b04bf777f3bd.png)

And while there, make sure to mark 1st two respawns as ground-special, because they dont appear in teleport list otherwise.

**Comment by felixmariotto** [comment]
![2020-05-04_104648](https://user-images.githubusercontent.com/46470486/80949628-a2bc2f80-8df4-11ea-8896-3443d820bd1d.jpg)
![2020-05-04_104704](https://user-images.githubusercontent.com/46470486/80949631-a5b72000-8df4-11ea-9008-23330221dcc1.jpg)
![2020-05-04_104520](https://user-images.githubusercontent.com/46470486/80949641-aa7bd400-8df4-11ea-8ce2-6422eaaf112f.jpg)
![2020-05-04_104552](https://user-images.githubusercontent.com/46470486/80949646-ac459780-8df4-11ea-8b84-f59dcad20371.jpg)

I uploaded an updated batch of map chunks that fixes all of these issues, thanks for catching it 👍
