### ISSUE TITLE
1.glb

### ISSUE THREAD

**Issue by makc** [felixmariotto/Edelweiss#18]
apart from seams I mentioned in https://github.com/felixmariotto/Edelweiss/issues/14#issuecomment-622145375, there are now shadow issues:

![Screen Shot 2020-05-03 at 17 06 07 ](https://user-images.githubusercontent.com/242577/80917755-62f83800-8d61-11ea-83a5-79a8810f1bf4.png)

did not notice them before because shadows keep getting optimized for me.

**Comment by felixmariotto** [comment]
I'm pretty sure that's because of the shape of the walls at the top, I didn't care as I knew nobody would see, but it turns out I should have done smooth edges

![2020-05-03_185757](https://user-images.githubusercontent.com/46470486/80920460-54fde380-8d70-11ea-996d-263a615c265f.jpg)

**Comment by makc** [comment]
also the wall on the left - maybe replace it by one single quad?

**Comment by makc** [comment]
I closed the other issues, but I would love to see you fixing this one, if possible

**Comment by felixmariotto** [comment]
![2020-05-04_104436](https://user-images.githubusercontent.com/46470486/80949773-f3cc2380-8df4-11ea-887c-88590bd8352f.jpg)

This is fixed with the new batch of map chunks I uploaded, thanks for catching the issue.
