### ISSUE TITLE
fxaa goes on and off

### ISSUE THREAD

**Issue by makc** [felixmariotto/Edelweiss#20]
this is very weird issue, actually, as you know my hardware is low-end so everything gets optimized away normally, so to get nice picture I do this:
![Screen Shot 2020-05-09 at 14 45 31 ](https://user-images.githubusercontent.com/242577/81474184-f61eeb00-9203-11ea-85cd-7925bbf7a0c4.png)
so with this, the optimizer is no-op, and I should get the fxaa pass always on, right?
However, I get these alternating images every 2 seconds or so:
![Screen Shot 2020-05-09 at 14 44 46 ](https://user-images.githubusercontent.com/242577/81474217-26ff2000-9204-11ea-82e1-16d53fec4fc3.png)
![Screen Shot 2020-05-09 at 14 45 05 ](https://user-images.githubusercontent.com/242577/81474218-2797b680-9204-11ea-87ad-4b8d2873a5b4.png)

**Comment by felixmariotto** [comment]
Mh that's weird indeed...

I tried it on my version (added return statement where you did, + tested in chrome devtool low-end mobile mode), but this didn't happen. In the same condition, I tried to log `console.log( optimizer.params.level )` before this block :
https://github.com/felixmariotto/Edelweiss/blob/f2d8e3955607b79fe64c50c257f1076734919d81/public/js/loop.js#L23-L32

But I got a steady 0, what happen if you do it in your fork ?

**Comment by makc** [comment]
yes I get always 0 as expeted.

**Comment by makc** [comment]
so it is something weird in the composer then... man, I do not want to go there

**Comment by felixmariotto** [comment]
To be honest I understand next to nothing at shaders, I just copy pasted three.js FXAA example 😅
If it's something with their example and you can reproduce in a fiddle, maybe they will help you ?
Do you think it may come from how I set it up here ? 
https://github.com/felixmariotto/Edelweiss/blob/f2d8e3955607b79fe64c50c257f1076734919d81/public/js/init.js#L26-L37

**Comment by felixmariotto** [comment]
Or if somehow you fire "resize" events every 2sec you would call this : 
https://github.com/felixmariotto/Edelweiss/blob/f2d8e3955607b79fe64c50c257f1076734919d81/public/js/main.js#L37-L42
But I don't know how it could produce this bug

**Comment by makc** [comment]
I just went to https://threejs.org/examples/?q=fxaa#webgl_postprocessing_fxaa and guess what :)
![Screen Shot 2020-05-10 at 12 29 46 ](https://user-images.githubusercontent.com/242577/81496732-0f826e80-92ba-11ea-8f6c-f726a705e4a3.png)

**Comment by felixmariotto** [comment]
?? weird ! Could it be related to your hardware ? Anyway maybe you should file a bug report to three.js

**Comment by makc** [comment]
Yep, I just did: https://github.com/mrdoob/three.js/issues/19331

**Comment by makc** [comment]
There might be something very broken about that browser. Sometimes I am getting the image with fxaa but not shadows:
![Screen Shot 2020-05-11 at 8 43 15 ](https://user-images.githubusercontent.com/242577/81531824-b111ca80-9363-11ea-9d17-05c42327a711.png)
Could it be because of this:
![Screen Shot 2020-05-11 at 8 46 03 ](https://user-images.githubusercontent.com/242577/81531970-f0401b80-9363-11ea-8f2f-50df8567ef56.png)
Going to turn that off and re-test...

**Comment by felixmariotto** [comment]
Wow the thing would turn shaders on and off without you knowing ? Is that Safari ?

**Comment by makc** [comment]
I just removed all the extensions, and it still does that. Welp, this is canary, it might itself be broken, actually. I kind of expected its bugs to only affect new stuff, webgl is not a new feature.

**Comment by felixmariotto** [comment]
I just remembered, I think you already mentioned a problem of inconsistent shadows in the game, it's probably related ? You wrote that in the thread in three.js forum I believe.

**Comment by makc** [comment]
right, when the character appeared to be in the shadow, but not everything
else.
