### ISSUE TITLE
Rotate the camera

### ISSUE THREAD

**Issue by cirosantilli** [felixmariotto/Edelweiss#3]
I need to see the other side, even if it is just untextured transparent invisible walls :cry: First person view mode would also be amazing of course.

**Comment by felixmariotto** [comment]
Hi ! 

You can have a basic always-behind-player camera by adding these lines : 
```javascript
camera.position.copy( CAMERA_DIRECTION );
camera.position.multiplyScalar( DEFAULT_CAMERA_DISTANCE * 0.9 );
camera.position.applyAxisAngle(
	cameraRayAxis,
	utils.toPiRange( player.charaGroup.rotation.y + (Math.PI) )
);
camera.position.add( player.position );
camera.lookAt( player.position );
return
```

At this line, right at the start of the cameraControl update function : 
https://github.com/felixmariotto/Edelweiss/blob/51aa1772d2da5bb069b2dbba83da789e7bc83af8/public/js/CameraControl.js#L190

![demo-camera-back](https://user-images.githubusercontent.com/46470486/78013374-acaac880-7346-11ea-95e9-f355f888793e.gif)

However, you must remap the controls, as currently the link between arrow keys and player direction is a constant.

The thing is, as you said, there is a lot of work to make the world look good if the player can look around in every direction ! Also there is a couple of secret bonus that entirely rely on the incapacity of the player to look around.

**Comment by felixmariotto** [comment]
Closing because no reply
