### ISSUE TITLE
disregard

### ISSUE THREAD

**Issue by hcavplatinum** [felixmariotto/Edelweiss#8]

**Comment by makc** [comment]
kinda true, if you have little stamina jumping onto climbable surface is out of question

**Comment by felixmariotto** [comment]
Yes, I observed that a lot of people try right away to jump on the wall and get confused. It's a level design issue, maybe they should start with 3 stamina, but then most people would not find the first edelweiss.

**Comment by makc** [comment]
It is the same with 3 bars, e g here:
![Screen Shot 2020-04-23 at 23 20 20 ](https://user-images.githubusercontent.com/242577/80150732-330aa100-85b9-11ea-9bf2-0dc7894b6bcc.png)
you jump on wall, and end up with most of your stamina gone:
![Screen Shot 2020-04-23 at 23 20 34 ](https://user-images.githubusercontent.com/242577/80150792-487fcb00-85b9-11ea-8ff2-c4ab64e2a77f.png)
if you try to climb, you can make it:
![Screen Shot 2020-04-23 at 23 20 48 ](https://user-images.githubusercontent.com/242577/80150828-5df4f500-85b9-11ea-864c-b3ba0edd28d8.png)
btw, note how the plant changes color in the bottom-right, there is a bug in one of glb files.

**Comment by makc** [comment]
maybe change 
```
    function reduceStamina( factor, update ) {

        params.stamina -= factor ;
```
to something like
```
    function reduceStamina( factor, update ) {

        params.stamina -= Math.min( factor, params.stamina / 3 ) ;
```
(or different magic number)

**Comment by makc** [comment]
> the plant changes color

this is super weird, the only glb I touched were 0 and 3, this plant is somewhere in 1, I just checked and it is the same as the one you currently have in AWS so you did not change it either. so what could I possibly do to glitch this plant? 🤔

**Comment by felixmariotto** [comment]
Mmmh that's weird.. I would say it's something with the textures. All the map chunks use almost the same texture, but some are a little bit different. So if somehow you switched or did something to the textures after loading the glbs, you could have unexpected results on very few faces like this.

**Comment by felixmariotto** [comment]
The plant looks green on your second screenshot... Do you see differences depending on the camera position ?

**Comment by makc** [comment]
yes
