### ISSUE TITLE
Tiles normals?

### ISSUE THREAD

**Issue by makc** [felixmariotto/Edelweiss#9]
just need a quick pointer here - as far as I see the tiles are essentially double-sided, right? The player gets hit-tested on both sides. But, is there any place in code where the tile actual direction defined/used? Like, if I were going to create a 3d tile with leaves, I need to know which side the leaves are supposed to go to.

**Comment by felixmariotto** [comment]
Hi makc,

the tiles direction has no importance in my model, and anyway as they are defined only by two points, I'm not sure if it's possible to define a direction, unless you add a 'normal' parameter.

For instance if we look here where I compute collision between the player hitbox and a horizontal tile : 
https://github.com/felixmariotto/Edelweiss/blob/67a8a63c518d727dd10985ccc3f380c1da3a027e/public/js/atlas.js#L726-L730
you can see that I compare player's position with the minimal X position of the two vectors defining my tile, whichever is the smallest, and then I compare player's position to the tallest X position of the two vectors. If player's position is between the two, and the same on the Y direction, then the player is positioned on top or under my tile. (after that I just check the height, to determine if the tile is cutting through the player's hitbox).

**Comment by makc** [comment]
> in your editor you must take care to always position the points according to this rule

what about existing tiles in your jsons? your editor also had some (implicit) rule to create the points, right?

**Comment by makc** [comment]
p.s. if you think about it, you only really need 1 point, the tile center. but if you did that, there would be no way to encode or infer the normal, so maybe it is good that you used 2

**Comment by felixmariotto** [comment]
> what about existing tiles in your jsons? your editor also had some (implicit) rule to create the points, right?

As it creates new tiles by rotating the currently selected tile on the edge between the current tile and the future tile, it consistently creates a tile with a normal inverse to the current one, so yes you're right, if we flip every new tile after it's created, normals should be consistents.

This should work :

```javascript
// flip the normal of one tile, whatever its orientation
function flipTile( tileVecs ) {

	const newVecs = [];
	const diffVec = new THREE.Vector3().copy( tileVecs[0] ).sub( tileVecs[1] );

	// loop through 'x', 'y', 'z'
	for ( dir of Object.keys( diffVec ) ) {

		if ( !diffVec[dir] ) continue ;

		// create a vector shifted of 1 in one direction
		const vecToChange = new THREE.Vector3().copy( tileVecs[1] )
		vecToChange[ dir ] += diffVec[ dir ];
		newVecs.push( vecToChange );
	};

	return newVecs ;
};

/*
flipTile([
	new THREE.Vector3( 0, 1, 2 ),
	new THREE.Vector3( 0, 0, 3 )
]);
--> [[0, 0, 2], [0, 1, 3]]

flipTile([
	new THREE.Vector3( 6, 0, 8 ),
	new THREE.Vector3( 7, 0, 7 )
]);
--> [[7, 0, 8], [6, 0, 7]]
*/
```

**Comment by makc** [comment]
> it consistently creates a tile with a normal inverse to the current one

so you mean if I make 4 floor tiles in a line, they will face up-down-up-down? this means the jsons would have to be filtered in order to get correct orienation, and no matter what there bound to be a corner cases where the filter gets the orientation wrong. maybe it is easier to just add the leafs on both sides.

**Comment by felixmariotto** [comment]
> so you mean if I make 4 floor tiles in a line, they will face up-down-up-down?

Yes, like a Chess board basically, after looking into it, it looks like its very consistent (without my knowing).

> this means the jsons would have to be filtered in order to get correct orienation

I rather thought above calling the snippet I've written above on `vec` and `verts[0]` before to call atlas.tempTile [here](https://github.com/felixmariotto/Edelweiss-Editor/blob/ec39601ff252e9e8db3101d77a2916c64bc84786/public/js/drawer.js#L247-L252). But yes there might be corner cases.

It's up to you, the leaves are lot of faces, so it may impact performance a bit if you put them on both sides, unless you use InstancedMesh.

**Comment by makc** [comment]
the whole thing actually stems from me being lazy about writing the code to track the tiles operations 😅 I was thinking, if the user adds the logic tiles, I would create the 3D tiles easily based on the character position, and this is non-issue. but then, what if they delete some tiles and add them back? glb file would already have a 3D in place, but there is no way for me to know it. Ideally I would just export 3D for the entire scenegraph and have people sort it out in the blender, and for this to work I need to process all the tiles they have saved in json. hope I make sense.

**Comment by makc** [comment]
> the leaves are lot of faces, so it may impact performance a bit if you put them on both sides, unless you use InstancedMesh

a valid concern if you do one mesh for the entire level. but if you have like, say, 4x4x4 tiles meshes that would be culled when the camera is not looking, it might not be too bad?

**Comment by felixmariotto** [comment]
OK, I misunderstood what you want to do. I thought you wanted to make proceduraly generated 3D map based on the tiles.

> a valid concern if you do one mesh for the entire level. but if you have like, say, 4x4x4 tiles meshes that would be culled when the camera is not looking, it might not be too bad?

Yes this can be an option. This is very mysterious for me how to balance huge-map-tiles-with-lots-of-tris / high-number-of-tiles-with-lots-of-draw-calls

**Comment by makc** [comment]
> I thought you wanted to make an entirely proceduraly generated 3D map based on the tiles.
well, yes? if someone does not know how to use the blender, the game would fail to load glb and proceed to create the 3D from the json alone.

but at the same time I want to keep the glb system as is now - because it allows to customize the map, you know, adding a little touch-up here and there, to look less minecraft-y. like these houses in the level 0. and, I do not want to implement elaborate system with cave door frames or random plants 😩 so... yes, I am just looking for the simplest hack to do this. maybe I should indeed just stick to new tiles only, and have some raycast test to determine if the tile already exists in glb 🤔

I guess with this issue I learned what I wanted to know, and now I just need to sort my own thoughts, thanks.

**Comment by makc** [comment]
btw @felixmariotto I have found the way to calculate the tile orientation that would have worked even if you only used center points. I only need to modify `atlas.intersectRay` to count intersections, and then shoot rays to the tiles out of the spot above the ground (e g starting player position). if there is odd number of intersections, including the target tile, it is facing the player. if there is even number of intersections, it is facing away. this is probably going to be super-slow, however.

**Comment by felixmariotto** [comment]
But how would you do to define a tile orientation ? I think you would still need a second vector for the normal, like THREE.Plane (and this latter has some interesting methods for intersection). But this would need an important refactoring of the tile collision part, I'm not sure it's worth...

**Comment by makc** [comment]
> how would you do to define a tile orientation

Do you mean about single point? Well, see, at 0,0,0 there could be 12 different tiles, right, but at 0,0.5,0 there could be only 4, and at 0,0.5,0.5 there could be only 1. The magic of central points :)
![](https://media1.giphy.com/media/12NUbkX6p4xOO4/200.gif)
